<a href="https://colab.research.google.com/github/sai14karthik/DIP/blob/main/AP21110010310_DIP_LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# DIP Lab Assignment 1
## N.Sai Karthik (AP21110010310) CSE-E

# Array

In [ ]:
a = np.array([0, 1, 2])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)
print(a[0])
print(a[1])
print(a[2])

(3,)
0
1
2


In [ ]:
a[0] = 5
print(a)

[5 1 2]


In [ ]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [ ]:
c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
d = np.random.random((3,3))
print(d)

[[0.08955694 0.63298739 0.98469759]
 [0.94318139 0.24054573 0.82478478]
 [0.38252522 0.12045412 0.80652948]]


In [ ]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
f = np.array([2, 3, 1, 0])
print(f)

[2 3 1 0]


In [ ]:
g = np.arange(20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [ ]:
i = np.arange(1, 8, dtype=float)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


In [ ]:
j = np.linspace(2, 4, 5)
print(j)

[2.  2.5 3.  3.5 4. ]


# Data Types

In [ ]:
x = np.array([0, 1])
y = np.array([2.0, 3.0])

In [ ]:
z = np.array([5, 6], dtype=np.int64)

In [ ]:
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


# Array Indexing

In [ ]:
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])

In [ ]:
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [ ]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [ ]:
cond = arr > 0
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# Basic array operations:

In [ ]:
a = np.array([1, 2, 5, 3])
print ("Adding 1 to every element:", a+1)

Adding 1 to every element: [2 3 6 4]


In [ ]:
print ("Subtracting 3 from each element:", a-3)

Subtracting 3 from each element: [-2 -1  2  0]


In [ ]:
print ("Multiplying each element by 10:", a*10)

Multiplying each element by 10: [10 20 50 30]


In [ ]:
print ("Squaring each element:", a**2)

Squaring each element: [ 1  4 25  9]


In [ ]:
print ("Doubled each element of original array:", a)

Doubled each element of original array: [1 2 5 3]


In [ ]:
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [ ]:
arr = np.array([[1, 5, 6],
[4, 7, 2],
[3, 1, 9]])
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
print ("Column-wise minimum elements:",arr.min(axis = 0))
print ("Sum of all array elements:",arr.sum())
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [ ]:
a = np.array([[1, 2],
[3, 4]])
b = np.array([[4, 3],
[2, 1]])
print ("Array sum:\n", a + b)

Array sum:
 [[5 5]
 [5 5]]


In [ ]:
print ("Array multiplication:\n", a*b)
print ("Matrix multiplication:\n", a.dot(b))

Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [ ]:
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [ ]:
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

# Linear Algebra using NumPy:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot product:", dot_product)


Dot product: 32


In [ ]:
a = np.random.rand(2, 4)
b = np.random.rand(4, 2)
c = np.random.rand(2, 2)
multi_dot_product = np.linalg.multi_dot([a, b, c])
print("Multi dot product:\n", multi_dot_product)


Multi dot product:
 [[0.4662668  0.5146067 ]
 [0.72733008 0.79956233]]


In [ ]:
a = np.array([1+2j, 3+4j])
b = np.array([5+6j, 7+8j])
vdot_product = np.vdot(a, b)
print("Vector dot product:", vdot_product)


Vector dot product: (70-8j)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
inner_product = np.inner(a, b)
print("Inner product:", inner_product)


Inner product: 32


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
outer_product = np.outer(a, b)
print("Outer product:\n", outer_product)


Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
matrix_product = np.matmul(a, b)
print("Matrix product:\n", matrix_product)


Matrix product:
 [[19 22]
 [43 50]]


In [ ]:
a = np.random.rand(2, 3, 4)
b = np.random.rand(4, 3, 2)
tensor_dot_product = np.tensordot(a, b, axes=([2, 1], [0, 1]))
print("Tensor dot product:\n", tensor_dot_product)


Tensor dot product:
 [[2.97210494 2.42159763]
 [2.2550686  2.80705802]]


In [ ]:
a = np.arange(25).reshape(5, 5)
b = np.arange(5)
einsum_result = np.einsum('ij,j->i', a, b)
print("Einsum result:", einsum_result)


Einsum result: [ 30  80 130 180 230]


In [ ]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
path_info = np.einsum_path('ij,jk->ik', a, b, optimize='optimal')
print("Einsum path:", path_info[0])


Einsum path: ['einsum_path', (0, 1)]


In [ ]:
a = np.array([[2, 3], [4, 5]])
matrix_power = np.linalg.matrix_power(a, 3)
print("Matrix power:\n", matrix_power)


Matrix power:
 [[116 153]
 [204 269]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
a = np.array([[1, 2], [2, 5]])
eigenvalues, eigenvectors = np.linalg.eigh(a)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [0.17157288 5.82842712]
Eigenvectors:
 [[-0.92387953  0.38268343]
 [ 0.38268343  0.92387953]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
eigenvalues = np.linalg.eigvals(a)
print("Eigenvalues:", eigenvalues)


Eigenvalues: [-0.37228132  5.37228132]
